general:
  front_end:
    _type: fastapi
    host: "0.0.0.0"
    port: 8080

llms:
  llm_nim:
    _type: nim
    base_url: ${LLM_BASE_URL}
    api_key: "not-needed"
    model_name: ${LLM_MODEL_NAME}

workflow:
  _type: chat_completion
  llm_name: llm_nim
  system_prompt: "You are a helpful AI assistant."
